import { Nature } from "./content/PokemonTypes";
interface NatureIndex {
    [name:string]: Nature
}

//Information From: https://pokemondb.net/ability
export const MASTER_ABILITY_INDEX:StringIndex = {
    "Adaptability": "Powers up moves of the same type.",
    "Aerilate": "Turns Normal-type moves into Flying-type moves.",
    "Aftermath": "Damages the attacker landing the finishing hit.",
    "Air Lock": "Eliminates the effects of weather.",
    "Analytic": "Boosts move power when the Pokémon moves last.",
    "Anger Point": "Maxes Attack after taking a critical hit.",
    "Anger Shell": "Lowers Defense/Sp. Def and raises Attack/Sp. Atk/Speed when HP drops below half.",
    "Anticipation": "Senses a foe's dangerous moves.",
    "Arena Trap": "Prevents the foe from fleeing.",
    "Armor Tail": "Prevents opponent using priority moves.",
    "Aroma Veil": "Protects allies from attacks that limit their move choices.",
    "As One": "Combines Unnerve and Chilling Neigh/Grim Neigh",
    "Aura Break": "Reduces power of Dark- and Fairy-type moves.",
    "Bad Dreams": "Reduces a sleeping foe's HP.",
    "Ball Fetch": "Retrieves a Poké Ball from a failed throw.",
    "Battery": "Raises power of teammates' Special moves.",
    "Battle Armor": "The Pokémon is protected against critical hits.",
    "Battle Bond": "Transform into Ash-Greninja after causing opponent to faint.",
    "Beads of Ruin": "Lowers Special Defense of all Pokémon except itself.",
    "Beast Boost": "The Pokémon boosts its most proficient stat each time it knocks out a Pokémon.",
    "Berserk": "Raises Special Attack when HP drops below half.",
    "Big Pecks": "Protects the Pokémon from Defense-lowering attacks.",
    "Blaze": "Powers up Fire-type moves in a pinch.",
    "Bulletproof": "Protects the Pokémon from ball and bomb moves.",
    "Cheek Pouch": "Restores additional HP when a Berry is consumed.",
    "Chilling Neigh": "Boosts Attack after knocking out a Pokémon.",
    "Chlorophyll": "Boosts the Pokémon's Speed in sunshine.",
    "Clear Body": "Prevents other Pokémon from lowering its stats.",
    "Cloud Nine": "Eliminates the effects of weather.",
    "Color Change": "Changes the Pokémon's type to the foe's move.",
    "Comatose": "The Pokémon is always asleep but can still attack.",
    "Commander": "Goes inside the mouth of an ally Dondozo if one is on the field.",
    "Competitive": "Sharply raises Special Attack when the Pokémon's stats are lowered.",
    "Compound Eyes": "The Pokémon's accuracy is boosted.",
    "Contrary": "Makes stat changes have an opposite effect.",
    "Corrosion": "The Pokémon can poison Steel and Poison types.",
    "Costar": "Copies ally's stat changes on entering battle.",
    "Cotton Down": "Lowers foe's Speed when hit.",
    "Cud Chew": "Can eat the same Berry twice.",
    "Curious Medicine": "Resets all stat changes upon entering battlefield.",
    "Cursed Body": "May disable a move used on the Pokémon.",
    "Cute Charm": "Contact with the Pokémon may cause infatuation.",
    "Damp": "Prevents the use of self-destructing moves.",
    "Dancer": "Copies the foe's Dance moves.",
    "Dark Aura": "Raises power of Dark type moves for all Pokémon in battle.",
    "Dauntless Shield": "Boosts Defense in battle.",
    "Dazzling": "Protects the Pokémon from high-priority moves.",
    "Defeatist": "Lowers stats when HP drops below half.",
    "Defiant": "Sharply raises Attack when the Pokémon's stats are lowered.",
    "Delta Stream": "Creates strong winds when the ability activates.",
    "Desolate Land": "Turns the sunlight extremely harsh when the ability activates.",
    "Disguise": "Avoids damage for one turn.",
    "Download": "Adjusts power according to a foe's defenses.",
    "Dragon's Maw ": "Powers up Dragon-type moves.",
    "Drizzle": "The Pokémon makes it rain when it enters a battle.",
    "Drought": "Turns the sunlight harsh when the Pokémon enters a battle.",
    "Dry Skin": "Reduces HP if it is hot. Water restores HP.",
    "Early Bird": "The Pokémon awakens quickly from sleep.",
    "Earth Eater": "Restores HP when hit by a Ground-type move.",
    "Effect Spore": "Contact may poison or cause paralysis or sleep.",
    "Electric Surge": "The Pokémon creates an Electric Terrain when it enters a battle.",
    "Electromorphosis": "Doubles power of the next Electric-type move when hit by an attack.",
    "Embody Aspect": "Boosts Attack/Defense/Sp. Def/Speed depending on the form.",
    "Emergency Exit": "Switches out when HP falls below",
    "Fairy Aura": "Raises power of Fairy type moves for all Pokémon in battle.",
    "Filter": "Reduces damage from super-effective attacks.",
    "Flame Body": "Contact with the Pokémon may burn the attacker.",
    "Flare Boost": "Powers up special attacks when burned.",
    "Flash Fire": "It powers up Fire-type moves if it's hit by one.",
    "Flower Gift": "Powers up party Pokémon when it is sunny.",
    "Flower Veil": "Prevents lowering of ally Grass-type Pokémon's stats.",
    "Fluffy": "Halves damage from contact moves, but doubles damage from Fire-type moves.",
    "Forecast": "Castform transforms with the weather.",
    "Forewarn": "Determines what moves a foe has.",
    "Friend Guard": "Reduces damage done to allies.",
    "Frisk": "The Pokémon can check a foe's held item.",
    "Full Metal Body": "Prevents other Pokémon from lowering its stats.",
    "Fur Coat": "Reduces damage from physical moves.",
    "Gale Wings": "Gives priority to Flying-type moves.",
    "Galvanize": "Normal-type moves become Electric-type moves and their power boosted.",
    "Gluttony": "Encourages the early use of a held Berry.",
    "Good as Gold": "Gives immunity to status moves.",
    "Gooey": "Contact with the Pokémon lowers the attacker's Speed stat.",
    "Gorilla Tactics": "Boosts the Pokémon's Attack stat but only allows the use of the first selected move.",
    "Grass Pelt": "Boosts the Defense stat in Grassy Terrain.",
    "Grassy Surge": "The Pokémon creates a Grassy Terrain when it enters a battle.",
    "Grim Neigh": "Boosts Special Attack after knocking out a Pokémon.",
    "Guard Dog": "Boosts Attack if intimidated, and prevents being forced to switch out.",
    "Gulp Missile": "Returns with a catch in its mouth after using Surf or Dive.",
    "Guts": "Boosts Attack if there is a status problem.",
    "Hadron Engine": "Creates an Electric Terrain when entering battle, and boosts Special Attack while active.",
    "Harvest": "May create another Berry after one is used.",
    "Healer": "May heal an ally's status conditions.",
    "Heatproof": "Weakens the power of Fire-type moves.",
    "Heavy Metal": "Doubles the Pokémon's weight.",
    "Honey Gather": "The Pokémon may gather Honey from somewhere.",
    "Hospitality": "Partially restores an ally's HP when it enters a battle.",
    "Huge Power": "Raises the Pokémon's Attack stat.",
    "Hunger Switch": "Changes forms each turn.",
    "Hustle": "Boosts the Attack stat, but lowers accuracy.",
    "Hydration": "Heals status problems if it is raining.",
    "Hyper Cutter": "Prevents other Pokémon from lowering Attack stat.",
    "Ice Body": "The Pokémon gradually regains HP in a hailstorm.",
    "Ice Face": "Avoids damage from Physical moves for one turn.",
    "Ice Scales": "Halves damage from Special moves.",
    "Illuminate": "Raises the likelihood of meeting wild Pokémon.",
    "Illusion": "Enters battle disguised as the last Pokémon in the party.",
    "Immunity": "Prevents the Pokémon from getting poisoned.",
    "Imposter": "It transforms itself into the Pokémon it is facing.",
    "Infiltrator": "Passes through the foe's barrier and strikes.",
    "Innards Out": "Deals damage upon fainting.",
    "Inner Focus": "The Pokémon is protected from flinching.",
    "Insomnia": "Prevents the Pokémon from falling asleep.",
    "Intimidate": "Lowers the foe's Attack stat.",
    "Intrepid Sword": "Boosts Attack in battle.",
    "Iron Barbs": "Inflicts damage to the Pokémon on contact.",
    "Iron Fist": "Boosts the power of punching moves.",
    "Justified": "Raises Attack when hit by a Dark-type move.",
    "Keen Eye": "Prevents other Pokémon from lowering accuracy.",
    "Klutz": "The Pokémon can't use any held items.",
    "Leaf Guard": "Prevents problems with status in sunny weather.",
    "Levitate": "Gives immunity to Ground type moves.",
    "Libero": "Changes the Pokémon's type to its last used move.",
    "Light Metal": "Halves the Pokémon's weight.",
    "Lightning Rod": "Draws in all Electric-type moves to up Sp. Attack.",
    "Limber": "The Pokémon is protected from paralysis.",
    "Lingering Aroma": "Contact changes the attacker's Ability to Lingering Aroma.",
    "Liquid Ooze": "Damages attackers using any draining move.",
    "Liquid Voice": "All sound-based moves become Water-type moves.",
    "Long Reach": "The Pokémon uses its moves without making contact with the target.",
    "Magic Bounce": "Reflects status- changing moves.",
    "Magic Guard": "Protects the Pokémon from indirect damage.",
    "Magician": "The Pokémon steals the held item of a Pokémon it hits with a move.",
    "Magma Armor": "Prevents the Pokémon from becoming frozen.",
    "Magnet Pull": "Prevents Steel-type Pokémon from escaping.",
    "Marvel Scale": "Ups Defense if there is a status problem.",
    "Mega Launcher": "Boosts the power of aura and pulse moves.",
    "Merciless": "The Pokémon's attacks become critical hits if the target is poisoned.",
    "Mimicry": "Changes type depending on the terrain.",
    "Mind's Eye": "Ignores opponent's Evasiveness, and allows Normal- and Fighting-type attacks to hit Ghosts.",
    "Minus": "Ups Sp. Atk if another Pokémon has Plus or Minus.",
    "Mirror Armor": "Reflects any stat-lowering effects.",
    "Misty Surge": "The Pokémon creates a Misty Terrain when it enters a battle.",
    "Mold Breaker": "Moves can be used regardless of Abilities.",
    "Moody": "Raises one stat and lowers another.",
    "Motor Drive": "Raises Speed if hit by an Electric-type move.",
    "Moxie": "Boosts Attack after knocking out any Pokémon.",
    "Multiscale": "Reduces damage when HP is full.",
    "Multitype": "Changes type to match the held Plate.",
    "Mummy": "Contact with this Pokémon spreads this Ability.",
    "Mycelium Might": "Status moves go last, but are not affected by the opponent's ability.",
    "Natural Cure": "All status problems heal when it switches out.",
    "Neuroforce": "Powers up moves that are super effective.",
    "Neutralizing Gas": "Neutralizes abilities of all Pokémon in battle.",
    "No Guard": "Ensures attacks by or against the Pokémon land.",
    "Normalize": "All the Pokémon's moves become the Normal type.",
    "Oblivious": "Prevents it from becoming infatuated.",
    "Opportunist": "Copies stat boosts by the opponent.",
    "Orichalcum Pulse": "Turns the sunlight harsh when entering battle, and boosts Attack while active.",
    "Overcoat": "Protects the Pokémon from weather damage.",
    "Overgrow": "Powers up Grass-type moves in a pinch.",
    "Own Tempo": "Prevents the Pokémon from becoming confused.",
    "Parental Bond": "Allows the Pokémon to attack twice.",
    "Pastel Veil": "Prevents the Pokémon and its allies from being poisoned.",
    "Perish Body": "When hit by a move that makes direct contact, the Pokémon and the attacker will faint after three turns unless they switch out of battle.",
    "Pickpocket": "Steals an item when hit by another Pokémon.",
    "Pickup": "The Pokémon may pick up items.",
    "Pixilate": "Turns Normal-type moves into Fairy-type moves.",
    "Plus": "Ups Sp. Atk if another Pokémon has Plus or Minus.",
    "Poison Heal": "Restores HP if the Pokémon is poisoned.",
    "Poison Point": "Contact with the Pokémon may poison the attacker.",
    "Poison Puppeteer": "Poisoned Pokémon also become confused.",
    "Poison Touch": "May poison targets when a Pokémon makes contact.",
    "Power Construct": "Changes form when HP drops below half.",
    "Power of Alchemy": "The Pokémon copies the Ability of a defeated ally.",
    "Power Spot": "Just being next to the Pokémon powers up moves.",
    "Prankster": "Gives priority to a status move.",
    "Pressure": "The Pokémon raises the foe's PP usage.",
    "Primordial Sea": "Makes it rain heavily when the ability activates.",
    "Prism Armor": "Reduces damage from super-effective attacks.",
    "Propeller Tail": "Ignores moves and abilities that draw in moves.",
    "Protean": "Changes the Pokémon's type to its last used move.",
    "Protosynthesis": "Raises highest stat in harsh sunlight, or if holding Booster Energy.",
    "Psychic Surge": "The Pokémon creates a Psychic Terrain when it enters a battle.",
    "Punk Rock": "Boosts sound-based moves and halves damage from the same moves.",
    "Pure Power": "Raises the Pokémon's Attack stat.",
    "Purifying Salt": "Protects from status conditions and halves damage from Ghost-type moves.",
    "Quark Drive": "Raises highest stat on Electric Terrain, or if holding Booster Energy.",
    "Queenly Majesty": "Prevents use of priority moves.",
    "Quick Draw": "",
    "Quick Feet": "Boosts Speed if there is a status problem.",
    "Rain Dish": "The Pokémon gradually regains HP in rain.",
    "Rattled": "Bug, Ghost or Dark type moves scare it and boost its Speed.",
    "Receiver": "Inherits an ally's ability when it faints.",
    "Reckless": "Powers up moves that have recoil damage.",
    "Refrigerate": "Turns Normal-type moves into Ice-type moves.",
    "Regenerator": "Restores a little HP when withdrawn from battle.",
    "Ripen": "Doubles the effect of berries.",
    "Rivalry": "Deals more damage to a Pokémon of same gender.",
    "RKS System": "Changes type depending on held item.",
    "Rock Head": "Protects the Pokémon from recoil damage.",
    "Rocky Payload": "Powers up Rock-type moves.",
    "Rough Skin": "Inflicts damage to the attacker on contact.",
    "Run Away": "Enables a sure getaway from wild Pokémon.",
    "Sand Force": "Boosts certain moves' power in a sandstorm.",
    "Sand Rush": "Boosts the Pokémon's Speed in a sandstorm.",
    "Sand Spit": "Creates a sandstorm when hit by an attack.",
    "Sand Stream": "The Pokémon summons a sandstorm in battle.",
    "Sand Veil": "Boosts the Pokémon's evasion in a sandstorm.",
    "Sap Sipper": "Boosts Attack when hit by a Grass-type move.",
    "Schooling": "Changes Wishiwashi to School Form.",
    "Scrappy": "Enables moves to hit Ghost-type Pokémon.",
    "Screen Cleaner": "Nullifies effects of Light Screen, Reflect, and Aurora Veil.",
    "Seed Sower": "Turns the ground into Grassy Terrain when the Pokémon is hit by an attack.",
    "Serene Grace": "Boosts the likelihood of added effects appearing.",
    "Shadow Shield": "Reduces damage when HP is full.",
    "Shadow Tag": "Prevents the foe from escaping.",
    "Sharpness": "Powers up slicing moves.",
    "Shed Skin": "The Pokémon may heal its own status problems.",
    "Sheer Force": "Removes added effects to increase move damage.",
    "Shell Armor": "The Pokémon is protected against critical hits.",
    "Shield Dust": "Blocks the added effects of attacks taken.",
    "Shields Down": "Changes stats when HP drops below half.",
    "Simple": "Doubles all stat changes.",
    "Skill Link": "Increases the frequency of multi-strike moves.",
    "Slow Start": "Temporarily halves Attack and Speed.",
    "Slush Rush": "Boosts the Pokémon's Speed stat in a hailstorm.",
    "Sniper": "Powers up moves if they become critical hits.",
    "Snow Cloak": "Raises evasion in a hailstorm.",
    "Snow Warning": "The Pokémon summons a hailstorm in battle.",
    "Solar Power": "In sunshine, Sp. Atk is boosted but HP decreases.",
    "Solid Rock": "Reduces damage from super-effective attacks.",
    "Soul-Heart": "Raises Special Attack when another Pokémon faints.",
    "Soundproof": "Gives immunity to sound-based moves.",
    "Speed Boost": "Its Speed stat is gradually boosted.",
    "Stakeout": "Deals double damage to Pokémon switching in.",
    "Stall": "The Pokémon moves after all other Pokémon do.",
    "Stalwart": "Ignores moves and abilities that draw in moves.",
    "Stamina": "Raises Defense when attacked.",
    "Stance Change": "Changes form depending on moves used.",
    "Static": "Contact with the Pokémon may cause paralysis.",
    "Steadfast": "Raises Speed each time the Pokémon flinches.",
    "Steam Engine": "Drastically raises Speed when hit by a Fire- or Water-type move.",
    "Steelworker": "Powers up Steel-type moves.",
    "Steely Spirit": "Powers up ally Pokémon's Steel-type moves.",
    "Stench": "The stench may cause the target to flinch.",
    "Sticky Hold": "Protects the Pokémon from item theft.",
    "Storm Drain": "Draws in all Water-type moves to up Sp. Attack.",
    "Strong Jaw": "Boosts the power of biting moves.",
    "Sturdy": "It cannot be knocked out with one hit.",
    "Suction Cups": "Negates all moves that force switching out.",
    "Super Luck": "Heightens the critical-hit ratios of moves.",
    "Supersweet Syrup": "Lowers opponent's Evasiveness when entering battle.",
    "Supreme Overlord": "Attack and Special Attack are boosted for each party Pokémon that has been defeated.",
    "Surge Surfer": "Doubles Speed during Electric Terrain.",
    "Swarm": "Powers up Bug-type moves in a pinch.",
    "Sweet Veil": "Prevents the Pokémon and allies from falling asleep.",
    "Swift Swim": "Boosts the Pokémon's Speed in rain.",
    "Sword of Ruin": "Lowers Defense of all Pokémon except itself.",
    "Symbiosis": "The Pokémon can pass an item to an ally.",
    "Synchronize": "Passes a burn, poison, or paralysis to the foe.",
    "Tablets of Ruin": "Lowers Attack of all Pokémon except itself.",
    "Tangled Feet": "Raises evasion if the Pokémon is confused.",
    "Tangling Hair": "Contact with the Pokémon lowers the attacker's Speed stat.",
    "Technician": "Powers up the Pokémon's weaker moves.",
    "Telepathy": "Anticipates an ally's attack and dodges it.",
    "Tera Shell": "Moves are not very effective when HP is full.",
    "Tera Shift": "Transforms into Terastal Form in battle.",
    "Teraform Zero": "Eliminates all effects of weather and terrain.",
    "Teravolt": "Moves can be used regardless of Abilities.",
    "Thermal Exchange": "Raises Attack when hit by a Fire-type move. Cannot be burned.",
    "Thick Fat": "Ups resistance to Fire- and Ice-type moves.",
    "Tinted Lens": "Powers up “not very effective” moves.",
    "Torrent": "Powers up Water-type moves in a pinch.",
    "Tough Claws": "Boosts the power of contact moves.",
    "Toxic Boost": "Powers up physical attacks when poisoned.",
    "Toxic Chain": "May cause bad poisoning.",
    "Toxic Debris": "Scatters poison spikes at the feet of the opposing team when the Pokémon takes damage from physical moves.",
    "Trace": "The Pokémon copies a foe's Ability.",
    "Transistor": "Powers up Electric-type moves.",
    "Triage": "Gives priority to restorative moves.",
    "Truant": "Pokémon can't attack on consecutive turns.",
    "Turboblaze": "Moves can be used regardless of Abilities.",
    "Unaware": "Ignores any stat changes in the Pokémon.",
    "Unburden": "Raises Speed if a held item is used.",
    "Unnerve": "Makes the foe nervous and unable to eat Berries.",
    "Unseen Fist": "Contact moves can strike through Protect/Detect.",
    "Vessel of Ruin": "Lowers Special Attack of all Pokémon except itself.",
    "Victory Star": "Boosts the accuracy of its allies and itself.",
    "Vital Spirit": "Prevents the Pokémon from falling asleep.",
    "Volt Absorb": "Restores HP if hit by an Electric-type move.",
    "Wandering Spirit": "Swaps abilities with opponents on contact.",
    "Water Absorb": "Restores HP if hit by a Water-type move.",
    "Water Bubble": "Halves damage from Fire-type moves, doubles power of Water-type moves used, and prevents burns.",
    "Water Compaction": "Sharply raises Defense when hit by a Water-type move.",
    "Water Veil": "Prevents the Pokémon from getting a burn.",
    "Weak Armor": "Physical attacks lower Defense and raise Speed.",
    "Well-Baked Body": "Immune to Fire-type moves, and Defense is sharply boosted.",
    "White Smoke": "Prevents other Pokémon from lowering its stats.",
    "Wimp Out": "Switches out when HP drops below half.",
    "Wind Power": "Doubles power of the next Electric-type move used, when hit by a wind move.",
    "Wind Rider": "Takes no damage from wind moves, and boosts Attack if hit by one.",
    "Wonder Guard": "Only supereffective moves will hit.",
    "Wonder Skin": "Makes status-changing moves more likely to miss.",
    "Zen Mode": "Changes form when HP drops below half.",
    "Zero to Hero": "Transforms into its Hero Form when switching out.",
}

//Information from : https://pokemondb.net/item/all#cat=hold
export const MASTER_ITEM_INDEX:StringIndex = {
    "Ability Capsule": "A capsule that allows a Pokémon with two Abilities to switch between these Abilities when it is used.",
    "Abomasite": "Enables Abomasnow to Mega Evolve during battle.",
    "Absolite": "Enables Absol to Mega Evolve during battle.",
    "Absorb Bulb": "A consumable bulb. If the holder is hit by a Water-type move, its Sp. Atk will rise.",
    "Adamant Crystal": " 	",
    "Adamant Orb": "Increases the power of Dragon- and Steel-type moves when held by Dialga.",
    "Adrenaline Orb": "Using it makes wild Pokémon more likely to call for help. If held by a Pokémon, it boosts Speed when intimidated. It can be used only once.",
    "Aerodactylite": "Enables Aerodactyl to Mega Evolve during battle.",
    "Aggronite": "Enables Aggron to Mega Evolve during battle.",
    "Air Balloon": "When held by a Pokémon, the Pokémon will float into the air. When the holder is attacked, this item will burst.",
    "Alakazite": "Enables Alakazam to Mega Evolve during battle.",
    "Aloraichium Z": "Allows Alolan Raichu to upgrade Thunderbolt to a Z-Move, Stoked Sparksurfer.",
    "Altarianite": "Enables Altaria to Mega Evolve during battle.",
    "Ampharosite": "Enables Ampharos to Mega Evolve during battle.",
    "Amulet Coin": "Doubles prize money if held.",
    "Assault Vest": "Raises Special Defense but prevents the use of status moves.",
    "Audinite": "Enables Audino to Mega Evolve during battle.",
    "Banettite": "Enables Banette to Mega Evolve during battle.",
    "Beedrillite": "Enables Beedrill to Mega Evolve during battle.",
    "Berry Sweet": "Evolves Milcery into Blueberry Flavor Alcremie.",
    "Big Root": "Recovers more HP from HP-stealing moves.",
    "Binding Band": "A band that increases the power of binding moves when held.",
    "Black Belt": "Increases the power of Fighting-type moves.",
    "Black Glasses": "Increases the power of Dark-type moves.",
    "Black Sludge": "A held item that gradually restores the HP of Poison-type Pokémon. It inflicts damage on all other types.",
    "Blank Plate": " 	",
    "Blastoisinite": "Enables Blastoise to Mega Evolve during battle.",
    "Blazikenite": "Enables Blaziken to Mega Evolve during battle.",
    "Blunder Policy": "Raises Speed sharply if its attack misses.",
    "Bright Powder": "Lowers the opponent's accuracy.",
    "Bug Gem": "Increases the power of a Bug-type move only once.",
    "Bug Memory": "Changes Silvally and its move Multi-Attack to Bug type.",
    "Buginium Z": "Allows the use of Savage Spin-Out, the Bug type Z-Move.",
    "Burn Drive": "Changes Techno Blast to a Fire-type move when held by Genesect.",
    "Cameruptite": "Enables Camerupt to Mega Evolve during battle.",
    "Cell Battery": "A consumable battery. If the holder is hit by an Electric-type move, its Attack will rise.",
    "Charcoal": "Increases the power of Fire-type moves.",
    "Charizardite X": "Enables Charizard to Mega Evolve during battle.",
    "Charizardite Y": "Enables Charizard to Mega Evolve during battle.",
    "Chill Drive": "Changes Techno Blast to an Ice-type move when held by Genesect.",
    "Chipped Pot": "Evolves Sinistea into Polteageist.",
    "Choice Band": "Raises Attack, but only one move can be used.",
    "Choice Scarf": "Raises Speed, but only one move can be used.",
    "Choice Specs": "Raises Special Attack, but only one move can be used.",
    "Cleanse Tag": "An item to be held by a Pokémon. It helps keep wild Pokémon away if the holder is the first one in the party.",
    "Clover Sweet": "Evolves Milcery into Clover Flavor Alcremie.",
    "Covert Cloak": "Conceals the holder, protecting it from the additional effects of moves.",
    "Cracked Pot": "Evolves Sinistea into Polteageist.",
    "Damp Rock": "A Pokémon held item that extends the duration of the move Rain Dance used by the holder.",
    "Dark Gem": "Increases the power of a Dark-type move only once.",
    "Dark Memory": "Changes Silvally and its move Multi-Attack to Dark type.",
    "Darkinium Z": "Allows the use of Black Hole Eclipse, the Dark type Z-Move.",
    "Decidium Z": "Allows Decidueye to upgrade Spirit Shackle to a Z-Move, Sinister Arrow Raid.",
    "Deep Sea Scale": "Increases Special Defense when held by Clamperl. Evolves Clamperl when traded holding the item.",
    "Deep Sea Tooth": "Increases Special Attack when held by Clamperl. Evolves Clamperl when traded holding the item.",
    "Destiny Knot": "A long, thin, bright-red string to be held by a Pokémon. If the holder becomes infatuated, the foe does too.",
    "Diancite": "Enables Diancie to Mega Evolve during battle.",
    "Douse Drive": "Changes Techno Blast to a Water-type move when held by Genesect.",
    "Draco Plate": "Increases power of Dragon-type moves. Changes Arceus' type to Dragon.",
    "Dragon Fang": "Increases the power of Dragon-type moves.",
    "Dragon Gem": "Increases the power of a Dragon-type move only once.",
    "Dragon Memory": "Changes Silvally and its move Multi-Attack to Dragon type.",
    "Dragonium Z": "Allows the use of Devastating Drake, the Dragon type Z-Move.",
    "Dread Plate": "Increases power of Dark-type moves. Changes Arceus' type to Dark.",
    "Dropped Item": "The Xtransceiver found at the Nimbasa City amusement park. It seems it belongs to a boy.",
    "Earth Plate": "Increases power of Ground-type moves. Changes Arceus' type to Ground.",
    "Eevium Z": "Allows Eevee to upgrade Last Resort to a Z-Move, Extreme Evoboost.",
    "Eject Button": "If the holder is hit by an attack, it will switch with another Pokémon in your party.",
    "Eject Pack": "The Pokémon switches out if its stats are lowered.",
    "Electric Gem": "Increases the power of an Electric-type move only once.",
    "Electric Memory": "Changes Silvally and its move Multi-Attack to Electric type.",
    "Electric Seed": "An item to be held by a Pokémon. It boosts Defense on Electric Terrain. It can only be used once.",
    "Electrium Z": "Allows the use of Gigavolt Havoc, the Electric type Z-Move.",
    "Elevator Key": "A card key that activates the elevator in Lysandre Labs. It is emblazoned with Team Flare's logo.",
    "Everstone": "An item to be held by a Pokémon. The Pokémon holding this peculiar stone is prevented from evolving.",
    "Eviolite": "A mysterious evolutionary lump. When held, it raises the Defense and Sp. Def of a Pokémon that can still evolve.",
    "Exp. Share": "An item to be held by a Pokémon. The holder gets a share of a battle's Exp. Points without battling.",
    "Expert Belt": "Increases the power of super-effective moves.",
    "Fairium Z": "Allows the use of Twinkle Tackle, the Fairy type Z-Move.",
    "Fairy Memory": "Changes Silvally and its move Multi-Attack to Fairy type.",
    "Fighting Gem": "Increases the power of a Fighting-type move only once.",
    "Fighting Memory": "Changes Silvally and its move Multi-Attack to Fighting type.",
    "Fightinium Z": "Allows the use of All-Out Pummeling, the Fighting type Z-Move.",
    "Fire Gem": "Increases the power of a Fire-type move only once.",
    "Fire Memory": "Changes Silvally and its move Multi-Attack to Fire type.",
    "Firium Z": "Allows the use of Inferno Overdrive, the Fire type Z-Move.",
    "Fist Plate": "Increases power of Fighting-type moves. Changes Arceus' type to Fighting.",
    "Flame Orb": "An item to be held by a Pokémon. It is a bizarre orb that inflicts a burn on the holder in battle.",
    "Flame Plate": "Increases power of Fire-type moves. Changes Arceus' type to Fire.",
    "Float Stone": "A very light stone. It reduces the weight of a Pokémon when held.",
    "Flower Sweet": "Evolves Milcery into Flower Flavor Alcremie.",
    "Flying Gem": "Increases the power of a Flying-type move only once.",
    "Flying Memory": "Changes Silvally and its move Multi-Attack to Flying type.",
    "Flyinium Z": "Allows the use of Supersonic Skystrike, the Flying type Z-Move.",
    "Focus Band": "An item to be held by a Pokémon. The holder may endure a potential KO attack, leaving it with just 1 HP.",
    "Focus Sash": "An item to be held by a Pokémon. If it has full HP, the holder will endure one potential KO attack, leaving 1 HP.",
    "Full Incense": "Holder always attacks last. Breeding Snorlax produces Munchlax when held.",
    "Galladite": "Enables Gallade to Mega Evolve during battle.",
    "Garchompite": "Enables Garchomp to Mega Evolve during battle.",
    "Gardevoirite": "Enables Gardevoir to Mega Evolve during battle.",
    "Gengarite": "Enables Gengar to Mega Evolve during battle.",
    "Ghost Gem": "Increases the power of a Ghost-type move only once.",
    "Ghost Memory": "Changes Silvally and its move Multi-Attack to Ghost type.",
    "Ghostium Z": "Allows the use of Never-Ending Nightmare, the Ghost type Z-Move.",
    "Glalitite": "Enables Glalie to Mega Evolve during battle.",
    "Grass Gem": "Increases the power of a Grass-type move only once.",
    "Grass Memory": "Changes Silvally and its move Multi-Attack to Grass type.",
    "Grassium Z": "Allows the use of Bloom Doom, the Grass type Z-Move.",
    "Grassy Seed": "An item to be held by a Pokémon. It boosts Defense on Grassy Terrain. It can only be used once.",
    "Grip Claw": "A Pokémon held item that extends the duration of multiturn attacks like Bind and Wrap.",
    "Griseous Core": " 	",
    "Griseous Orb": "Increases the power of Dragon- and Ghost-type moves when held by Giratina, and changes it to Origin Forme.",
    "Grit Dust": "Raises EVs by 1 in Legends: Arceus, when current EVs are between 0-2.",
    "Grit Gravel": "Raises EVs by 1 in Legends: Arceus, when current EVs are between 3-5.",
    "Grit Pebble": "Raises EVs by 1 in Legends: Arceus, when current EVs are between 6-8.",
    "Grit Rock": "Raises EVs by 1 in Legends: Arceus, when current EVs are between 8-9.",
    "Ground Gem": "Increases the power of a Ground-type move only once.",
    "Ground Memory": "Changes Silvally and its move Multi-Attack to Ground type.",
    "Groundium Z": "Allows the use of Tectonic Rage, the Ground type Z-Move.",
    "Grubby Hanky": "A handkerchief dropped by a regular at Café Warehouse. It smells faintly like a Pokémon.",
    "Gyaradosite": "Enables Gyarados to Mega Evolve during battle.",
    "Hard Stone": "Increases the power of Rock-type moves.",
    "Heat Rock": "A Pokémon held item that extends the duration of the move Sunny Day used by the holder.",
    "Heavy-Duty Boots": "Protects the holder from traps set on the battlefield.",
    "Heracronite": "Enables Heracross to Mega Evolve during battle.",
    "Hi-tech Earbuds": "Strange earbuds that allow you to freely control the volume of various sounds.",
    "Honor Of Kalos": "A precious symbol that is awarded only to an individual who has done great things for the Kalos region.",
    "Houndoominite": "Enables Houndoom to Mega Evolve during battle.",
    "Ice Gem": "Increases the power of an Ice-type move only once.",
    "Ice Memory": "Changes Silvally and its move Multi-Attack to Ice type.",
    "Icicle Plate": "Increases power of Ice-type moves. Changes Arceus' type to Ice.",
    "Icium Z": "Allows the use of Subzero Slammer, the Ice type Z-Move.",
    "Icy Rock": "A Pokémon held item that extends the duration of the move Hail used by the holder.",
    "Incinium Z": "Allows Incineroar to upgrade Darkest Lariat to a Z-Move, Malicious Moonsault.",
    "Insect Plate": "Increases power of Bug-type moves. Changes Arceus' type to Bug.",
    "Intriguing Stone": "A rather curious stone that might appear to be valuable to some. It's all in the eye of the beholder.",
    "Iron Ball": "A Pokémon held item that cuts Speed. It makes Flying-type and levitating holders susceptible to Ground moves.",
    "Iron Plate": "Increases power of Steel-type moves. Changes Arceus' type to Steel.",
    "Kangaskhanite": "Enables Kangaskhan to Mega Evolve during battle.",
    "King's Rock": "May cause opponent to flinch. Evolves Poliwhirl and Slowpoke when traded holding the item.",
    "Kommonium Z": "Allows Kommo-o to upgrade Clanging Scales to a Z-Move, Clangorous Soulblaze.",
    "Lagging Tail": "Holder always attacks last.",
    "Latiasite": "Enables Latias to Mega Evolve during battle.",
    "Latiosite": "Enables Latios to Mega Evolve during battle.",
    "Lax Incense": "Lowers the opponent's accuracy. Breeding Wobbuffet produces Wynaut when held.",
    "Leek": "Increases critical-hit ratio when held by Farfetch'd.",
    "Leftovers": "An item to be held by a Pokémon. The holder's HP is gradually restored during battle.",
    "Legend Plate": " 	",
    "Life Orb": "Increases the power of moves, but loses HP each turn.",
    "Light Ball": "An item to be held by PIKACHU. It is a puzzling orb that raises the Attack and Sp. Atk stat.",
    "Light Clay": "A Pokémon held item that extends the duration of barrier moves like Light Screen and Reflect used by the holder.",
    "Loaded Dice": "Makes multi-strike moves more likely to hit more times.",
    "Looker Ticket": "A ticket that was handmade by Looker. It's decorated with a liberal amount of glittery paint.",
    "Lopunnite": "Enables Lopunny to Mega Evolve during battle.",
    "Love Sweet": "Evolves Milcery into Heart Flavor Alcremie.",
    "Lucarionite": "Enables Lucario to Mega Evolve during battle.",
    "Luck Incense": "Doubles prize money if held. Breeding Chansey or Blissey produces Happiny when held.",
    "Lucky Egg": "An item to be held by a Pokémon. It is an egg filled with happiness that earns extra Exp. Points in battle.",
    "Lucky Punch": "Increases critical-hit ratio when held by Chansey.",
    "Luminous Moss": "Raises Special Defense if hit by a Water-type move.",
    "Lunalium Z": "Allows Lunala to upgrade Moongeist Beam to a Z-Move, Menacing Moonraze Maelstrom.",
    "Lustrous Globe": " 	",
    "Lustrous Orb": "Increases the power of Dragon- and Water-type moves when held by Palkia.",
    "Lycanium Z": "Allows Lycanroc to upgrade Stone Edge to a Z-Move, Splintered Stormshards.",
    "Macho Brace": "An item to be held by a Pokémon. It is a stiff and heavy brace that promotes strong growth but lowers Speed.",
    "Magnet": "Increases the power of Electric-type moves.",
    "Manectite": "Enables Manectric to Mega Evolve during battle.",
    "Marshadium Z": "Allows Marshadow to upgrade Spectral Thief to a Z-Move, Soul-Stealing 7-Star Strike.",
    "Mawilite": "Enables Mawile to Mega Evolve during battle.",
    "Meadow Plate": "Increases power of Grass-type moves. Changes Arceus' type to Grass.",
    "Medichamite": "Enables Medicham to Mega Evolve during battle.",
    "Mental Herb": "An item to be held by a Pokémon. It snaps the holder out of infatuation. It can be used only once.",
    "Metagrossite": "Enables Metagross to Mega Evolve during battle.",
    "Metal Coat": "Increases the power of Steel-type moves. Evolves Onix and Scyther when traded holding the item.",
    "Metal Powder": "Increases Defense when held by Ditto.",
    "Metronome": "Increases the power of moves used consecutively.",
    "Mewnium Z": "Allows Mew to upgrade Psychic to a Z-Move, Genesis Supernova.",
    "Mewtwonite X": "Enables Mewtwo to Mega Evolve during battle.",
    "Mewtwonite Y": "Enables Mewtwo to Mega Evolve during battle.",
    "Mimikium Z": "Allows Mimikyu to upgrade Play Rough to a Z-Move, Let's Snuggle Forever.",
    "Mind Plate": "Increases power of Psychic-type moves. Changes Arceus' type to Psychic.",
    "Miracle Seed": "Increases the power of Grass-type moves.",
    "Mirror Herb": "Copies an opponent's stat increases when consumed.",
    "Misty Seed": "An item to be held by a Pokémon. It boosts Sp. Def on Misty Terrain. It can only be used once.",
    "Muscle Band": "Increases the power of Physical-category moves.",
    "Mystic Water": "Increases the power of Water-type moves.",
    "Never-Melt Ice": "Increases the power of Ice-type moves.",
    "Normal Gem": "Increases the power of a Normal-type move only once.",
    "Normalium Z": "Allows the use of Breakneck Blitz, the Normal type Z-Move.",
    "Odd Incense": "Increases the power of Psychic-type moves. Breeding Mr. Mime produces Mime Jr. when held.",
    "Pass Orb": "A mysterious orb containing the power of the Unova region, to be used when generating Pass Power.",
    "Pidgeotite": "Enables Pidgeot to Mega Evolve during battle.",
    "Pikanium Z": "Allows Pikachu to upgrade Volt Tackle to a Z-Move, Catastropika.",
    "Pikashunium Z": "Allows Pikachu in a cap to upgrade Thunderbolt to a Z-Move, 10,000,000 Volt Thunderbolt.",
    "Pink Nectar": "The flower nectar obtained at the flowering shrubs on Royal Avenue. It changes the form of certain species of Pokémon.",
    "Pinsirite": "Enables Pinsir to Mega Evolve during battle.",
    "Pixie Plate": "Increases power of Fairy-type moves. Changes Arceus' type to Fairy.",
    "Plasma Card": "A card key needed to enter the password inside the Plasma Frigate.",
    "Poison Barb": "Increases the power of Poison-type moves.",
    "Poison Gem": "Increases the power of a Poison-type move only once.",
    "Poison Memory": "Changes Silvally and its move Multi-Attack to Poison type.",
    "Poisonium Z": "Allows the use of Acid Downpour, the Poison type Z-Move.",
    "Power Anklet": "A Pokémon held item that promotes Speed gain on leveling, but reduces the Speed stat.",
    "Power Band": "A Pokémon held item that promotes Sp. Def gain on leveling, but reduces the Speed stat.",
    "Power Belt": "A Pokémon held item that promotes Defense gain on leveling, but reduces the Speed stat.",
    "Power Bracer": "A Pokémon held item that promotes Attack gain on leveling, but reduces the Speed stat.",
    "Power Herb": "A single-use item to be held by a Pokémon. It allows the immediate use of a move that charges on the first turn.",
    "Power Lens": "A Pokémon held item that promotes Sp. Atk gain on leveling, but reduces the Speed stat.",
    "Power Plant Pass": "This pass serves as an ID card for gaining access to the power plant that lies along Route 13.",
    "Power Weight": "A Pokémon held item that promotes HP gain on leveling, but reduces the Speed stat.",
    "Primarium Z": "Allows Primarina to upgrade Sparkling Aria to a Z-Move, Oceanic Operetta.",
    "Prison Bottle": "Transforms Hoopa Confined to Hoopa Unbound.",
    "Prof's Letter": "A letter that Professor Sycamore wrote to your mother. A faint but pleasant perfume seems to cling to the paper.",
    "Protective Pads": "An item to be held by a Pokémon. These pads protect the holder from effects caused by making direct contact with the target.",
    "Psychic Gem": "Increases the power of a Psychic-type move only once.",
    "Psychic Memory": "Changes Silvally and its move Multi-Attack to Psychic type.",
    "Psychic Seed": "An item to be held by a Pokémon. It boosts Sp. Def on Psychic Terrain. It can only be used once.",
    "Psychium Z": "Allows the use of Shattered Psyche, the Psychic type Z-Move.",
    "Pure Incense": "Descreases the likelihood of meeting wild Pokémon. Breeding Chimecho produces Chingling when held.",
    "Purple Nectar": "A flower nectar obtained at Poni Meadow. It changes the form of certain species of Pokémon.",
    "Quick Claw": "An item to be held by a Pokémon. A light, sharp claw that lets the bearer move first occasionally.",
    "Quick Powder": "Increases Speed when held by Ditto.",
    "Razor Claw": "Increases critical-hit ratio. Evolves Sneasel when held at night.",
    "Razor Fang": "May cause opponent to flinch. Evolves Gligar when held at night.",
    "Red Card": "A card with a mysterious power. When the holder is struck by a foe, the attacker is removed from battle.",
    "Red Nectar": "A flower nectar obtained at Ula'ula Meadow. It changes the form of certain species of Pokémon.",
    "Ribbon Sweet": "Evolves Milcery into Ribbon Flavor Alcremie.",
    "Ring Target": "Moves that would otherwise have no effect will land on the Pokémon that holds it.",
    "Rock Gem": "Increases the power of a Rock-type move only once.",
    "Rock Incense": "Increases the power of Rock-type moves. Breeding Sudowoodo produces Bonsly when held.",
    "Rock Memory": "Changes Silvally and its move Multi-Attack to Rock type.",
    "Rockium Z": "Allows the use of Continental Crush, the Rock type Z-Move.",
    "Rocky Helmet": "If the holder of this item takes damage, the attacker will also be damaged upon contact.",
    "Room Service": "Lowers the Pokémon's speed during Trick Room.",
    "Rose Incense": "Increases the power of Grass-type moves. Breeding Roselia or Roserade produces Budew when held.",
    "Sablenite": "Enables Sableye to Mega Evolve during battle.",
    "Safety Goggles": "Prevents damage from weather and powder.",
    "Salamencite": "Enables Salamence to Mega Evolve during battle.",
    "Sceptilite": "Enables Sceptile to Mega Evolve during battle.",
    "Scizorite": "Enables Scizor to Mega Evolve during battle.",
    "Scope Lens": "Increases critical-hit ratio.",
    "Sea Incense": "Increases the power of Water-type moves. Breeding Marill or Azumarill produces Azurill when held.",
    "Sharp Beak": "Increases the power of Flying-type moves.",
    "Sharpedonite": "Enables Sharpedo to Mega Evolve during battle.",
    "Shed Shell": "A tough, discarded carapace to be held by a Pokémon. It enables the holder to switch with a waiting Pokémon in battle.",
    "Shell Bell": "An item to be held by a Pokémon. The holder's HP is restored a little every time it inflicts damage.",
    "Shock Drive": "Changes Techno Blast to an Electric-type move when held by Genesect.",
    "Silk Scarf": "Increases the power of Normal-type moves.",
    "Silver Powder": "Increases the power of Bug-type moves.",
    "Sky Plate": "Increases power of Flying-type moves. Changes Arceus' type to Flying.",
    "Slowbronite": "Enables Slowbro to Mega Evolve during battle.",
    "Smoke Ball": "An item to be held by a Pokémon. It enables the holder to flee from any wild Pokémon without fail.",
    "Smooth Rock": "A Pokémon held item that extends the duration of the move Sandstorm used by the holder.",
    "Snorlium Z": "Allows Snorlax to upgrade Giga Impact to a Z-Move, Pulverizing Pancake.",
    "Snowball": "Raises Attack if hit by an Ice-type move.",
    "Soft Sand": "Increases the power of Ground-type moves.",
    "Solganium Z": "Allows Solgaleo to upgrade Sunsteel Strike to a Z-Move, Searing Sunraze Smash.",
    "Soothe Bell": "An item to be held by a Pokémon. It is a bell with a comforting chime that calms the holder and makes it friendly.",
    "Soul Dew": "Increases the power of Psychic- and Dragon-type moves when held by Latios or Latias. Increases Sp.Atk/Sp.Def prior to Gen 7.",
    "Spell Tag": "Increases the power of Ghost-type moves.",
    "Splash Plate": "Increases power of Water-type moves. Changes Arceus' type to Water.",
    "Spooky Plate": "Increases power of Ghost-type moves. Changes Arceus' type to Ghost.",
    "Star Sweet": "Evolves Milcery into Star Flavor Alcremie.",
    "Steel Gem": "Increases the power of a Steel-type move only once.",
    "Steel Memory": "Changes Silvally and its move Multi-Attack to Steel type.",
    "Steelium Z": "Allows the use of Corkscrew Crash, the Steel type Z-Move.",
    "Steelixite": "Enables Steelix to Mega Evolve during battle.",
    "Sticky Barb": "A held item that damages the holder on every turn. It may latch on to foes and allies that touch the holder.",
    "Stone Plate": "Increases power of Rock-type moves. Changes Arceus' type to Rock.",
    "Strawberry Sweet": "Evolves Milcery into Strawberry Flavor Alcremie.",
    "Swampertite": "Enables Swampert to Mega Evolve during battle.",
    "Sweet Apple": "Evolves Applin into Appletun.",
    "Syrupy Apple": "Evolves Applin into Dipplin.",
    "Tapunium Z": "Allows the Tapus to upgrade Nature's Madness to a Z-Move, Guardian of Alola.",
    "Tart Apple": "Evolves Applin into Flapple.",
    "Terrain Extender": "An item to be held by a Pokémon. It extends the duration of the terrain caused by the holder's move or Ability.",
    "Thick Club": "Increases Attack when held by Cubone or Marowak.",
    "Throat Spray": "Raises Sp. Atk when a sound-based move is used.",
    "Toxic Orb": "An item to be held by a Pokémon. It is a bizarre orb that badly poisons the holder in battle.",
    "Toxic Plate": "Increases power of Poison-type moves. Changes Arceus' type to Poison.",
    "Twisted Spoon": "Increases the power of Psychic-type moves.",
    "Tyranitarite": "Enables Tyranitar to Mega Evolve during battle.",
    "Ultranecrozium Z": "Allows Ultra Necrozma to upgrade Photon Geyser to a Z-Move, Light That Burns the Sky.",
    "Utility Umbrella": "An item to be held by a Pokémon. This sturdy umbrella protects the holder from the effects of weather.",
    "Venusaurite": "Enables Venusaur to Mega Evolve during battle.",
    "Water Gem": "Increases the power of a Water-type move only once.",
    "Water Memory": "Changes Silvally and its move Multi-Attack to Water type.",
    "Waterium Z": "Allows the use of Hydro Vortex, the Water type Z-Move.",
    "Wave Incense": "Increases the power of Water-type moves. Breeding Mantine produces Mantyke when held.",
    "Weakness Policy": "Sharply raises Attack and Special Attack if hit by a super-effective move.",
    "White Herb": "An item to be held by a POKéMON. It restores any lowered stat in battle. It can be used only once.",
    "Wide Lens": "Increases the accuracy of moves.",
    "Wise Glasses": "Increases the power of Special-category moves.",
    "Yellow Nectar": "A flower nectar obtained at Melemele Meadow. It changes the form of certain species of Pokémon.",
    "Zap Plate": "Increases power of Electric-type moves. Changes Arceus' type to Electric.",
    "Zoom Lens": "Raises a move's accuracy if the holder moves after its target."
}

export const MASTER_NATURE_INDEX: NatureIndex = {
    ADAMANT: {inc: "Attack",      dec: "Sp. Attack"},
    BASHFUL: {inc: "Sp. Attack",  dec: "Sp. Attack"},
    BOLD:    {inc: "Defense",     dec: "Attack"},
    BRAVE:   {inc: "Attack",      dec: "Speed"},
    CALM:    {inc: "Sp. Defence", dec: "Attack"},
    CAREFUL: {inc: "Sp. Defense", dec: "Sp. Attack"},
    DOCILE:  {inc: "Defense",     dec: "Defense"},
    GENTLE:  {inc: "Sp. Defense", dec: "Defense"},
    HARDY:   {inc: "Attack",      dec: "Attack"},
    HASTY:   {inc: "Speed",       dec: "Defense"},
    IMPISH:  {inc: "Defense",     dec: "Sp. Attack"},
    JOLLY:   {inc: "Speed",       dec: "Sp. Attack"},
    LAX:     {inc: "Defense",     dec: "Sp. Defense"},
    LONELY:  {inc: "Attack",      dec: "Defense"},
    MILD:    {inc: "Sp. Attack",  dec: "Defense"},
    MODEST:  {inc: "Sp. Attack",  dec: "Attack"},
    NAIVE:   {inc: "Speed",       dec: "Sp. Defense"},
    NAUGHTY: {inc: "Attack",      dec: "Sp. Defense"},
    QUIET:   {inc: "Sp. Attack",  dec: "Speed"},
    QUIRKY:  {inc: "Sp. Defence", dec: "Sp. Defense"},
    RASH:    {inc: "Sp. Attack",  dec: "Sp. Defense"},
    RELAXED: {inc: "Defense",     dec: "Speed"},
    SASSY:   {inc: "Sp. Defence", dec: "Speed"},
    SERIOUS: {inc: "Speed",       dec: "Speed"},
    TIMID:   {inc: "Speed",       dec: "Attack"},
}

//Scraped for Serebii
export const MASTER_POKEMON_LIST = [
    "Bulbasaur",
    "Ivysaur",
    "Venusaur",
    "Charmander",
    "Charmeleon",
    "Charizard",
    "Squirtle",
    "Wartortle",
    "Blastoise",
    "Caterpie",
    "Metapod",
    "Butterfree",
    "Weedle",
    "Kakuna",
    "Beedrill",
    "Pidgey",
    "Pidgeotto",
    "Pidgeot",
    "Rattata",
    "Raticate",
    "Spearow",
    "Fearow",
    "Ekans",
    "Arbok",
    "Pikachu",
    "Raichu",
    "Sandshrew",
    "Sandslash",
    "Nidoran♀",
    "Nidorina",
    "Nidoqueen",
    "Nidoran♂",
    "Nidorino",
    "Nidoking",
    "Clefairy",
    "Clefable",
    "Vulpix",
    "Ninetales",
    "Jigglypuff",
    "Wigglytuff",
    "Zubat",
    "Golbat",
    "Oddish",
    "Gloom",
    "Vileplume",
    "Paras",
    "Parasect",
    "Venonat",
    "Venomoth",
    "Diglett",
    "Dugtrio",
    "Meowth",
    "Persian",
    "Psyduck",
    "Golduck",
    "Mankey",
    "Primeape",
    "Growlithe",
    "Arcanine",
    "Poliwag",
    "Poliwhirl",
    "Poliwrath",
    "Abra",
    "Kadabra",
    "Alakazam",
    "Machop",
    "Machoke",
    "Machamp",
    "Bellsprout",
    "Weepinbell",
    "Victreebel",
    "Tentacool",
    "Tentacruel",
    "Geodude",
    "Graveler",
    "Golem",
    "Ponyta",
    "Rapidash",
    "Slowpoke",
    "Slowbro",
    "Magnemite",
    "Magneton",
    "Farfetch'd",
    "Doduo",
    "Dodrio",
    "Seel",
    "Dewgong",
    "Grimer",
    "Muk",
    "Shellder",
    "Cloyster",
    "Gastly",
    "Haunter",
    "Gengar",
    "Onix",
    "Drowzee",
    "Hypno",
    "Krabby",
    "Kingler",
    "Voltorb",
    "Electrode",
    "Exeggcute",
    "Exeggutor",
    "Cubone",
    "Marowak",
    "Hitmonlee",
    "Hitmonchan",
    "Lickitung",
    "Koffing",
    "Weezing",
    "Rhyhorn",
    "Rhydon",
    "Chansey",
    "Tangela",
    "Kangaskhan",
    "Horsea",
    "Seadra",
    "Goldeen",
    "Seaking",
    "Staryu",
    "Starmie",
    "Mr. Mime",
    "Scyther",
    "Jynx",
    "Electabuzz",
    "Magmar",
    "Pinsir",
    "Tauros",
    "Magikarp",
    "Gyarados",
    "Lapras",
    "Ditto",
    "Eevee",
    "Vaporeon",
    "Jolteon",
    "Flareon",
    "Porygon",
    "Omanyte",
    "Omastar",
    "Kabuto",
    "Kabutops",
    "Aerodactyl",
    "Snorlax",
    "Articuno",
    "Zapdos",
    "Moltres",
    "Dratini",
    "Dragonair",
    "Dragonite",
    "Mewtwo",
    "Mew",
    "Chikorita",
    "Bayleef",
    "Meganium",
    "Cyndaquil",
    "Quilava",
    "Typhlosion",
    "Totodile",
    "Croconaw",
    "Feraligatr",
    "Sentret",
    "Furret",
    "Hoothoot",
    "Noctowl",
    "Ledyba",
    "Ledian",
    "Spinarak",
    "Ariados",
    "Crobat",
    "Chinchou",
    "Lanturn",
    "Pichu",
    "Cleffa",
    "Igglybuff",
    "Togepi",
    "Togetic",
    "Natu",
    "Xatu",
    "Mareep",
    "Flaaffy",
    "Ampharos",
    "Bellossom",
    "Marill",
    "Azumarill",
    "Sudowoodo",
    "Politoed",
    "Hoppip",
    "Skiploom",
    "Jumpluff",
    "Aipom",
    "Sunkern",
    "Sunflora",
    "Yanma",
    "Wooper",
    "Quagsire",
    "Espeon",
    "Umbreon",
    "Murkrow",
    "Slowking",
    "Misdreavus",
    "Unown",
    "Wobbuffet",
    "Girafarig",
    "Pineco",
    "Forretress",
    "Dunsparce",
    "Gligar",
    "Steelix",
    "Snubbull",
    "Granbull",
    "Qwilfish",
    "Scizor",
    "Shuckle",
    "Heracross",
    "Sneasel",
    "Teddiursa",
    "Ursaring",
    "Slugma",
    "Magcargo",
    "Swinub",
    "Piloswine",
    "Corsola",
    "Remoraid",
    "Octillery",
    "Delibird",
    "Mantine",
    "Skarmory",
    "Houndour",
    "Houndoom",
    "Kingdra",
    "Phanpy",
    "Donphan",
    "Porygon2",
    "Stantler",
    "Smeargle",
    "Tyrogue",
    "Hitmontop",
    "Smoochum",
    "Elekid",
    "Magby",
    "Miltank",
    "Blissey",
    "Raikou",
    "Entei",
    "Suicune",
    "Larvitar",
    "Pupitar",
    "Tyranitar",
    "Lugia",
    "Ho-Oh",
    "Celebi",
    "Treecko",
    "Grovyle",
    "Sceptile",
    "Torchic",
    "Combusken",
    "Blaziken",
    "Mudkip",
    "Marshtomp",
    "Swampert",
    "Poochyena",
    "Mightyena",
    "Zigzagoon",
    "Linoone",
    "Wurmple",
    "Silcoon",
    "Beautifly",
    "Cascoon",
    "Dustox",
    "Lotad",
    "Lombre",
    "Ludicolo",
    "Seedot",
    "Nuzleaf",
    "Shiftry",
    "Taillow",
    "Swellow",
    "Wingull",
    "Pelipper",
    "Ralts",
    "Kirlia",
    "Gardevoir",
    "Surskit",
    "Masquerain",
    "Shroomish",
    "Breloom",
    "Slakoth",
    "Vigoroth",
    "Slaking",
    "Nincada",
    "Ninjask",
    "Shedinja",
    "Whismur",
    "Loudred",
    "Exploud",
    "Makuhita",
    "Hariyama",
    "Azurill",
    "Nosepass",
    "Skitty",
    "Delcatty",
    "Sableye",
    "Mawile",
    "Aron",
    "Lairon",
    "Aggron",
    "Meditite",
    "Medicham",
    "Electrike",
    "Manectric",
    "Plusle",
    "Minun",
    "Volbeat",
    "Illumise",
    "Roselia",
    "Gulpin",
    "Swalot",
    "Carvanha",
    "Sharpedo",
    "Wailmer",
    "Wailord",
    "Numel",
    "Camerupt",
    "Torkoal",
    "Spoink",
    "Grumpig",
    "Spinda",
    "Trapinch",
    "Vibrava",
    "Flygon",
    "Cacnea",
    "Cacturne",
    "Swablu",
    "Altaria",
    "Zangoose",
    "Seviper",
    "Lunatone",
    "Solrock",
    "Barboach",
    "Whiscash",
    "Corphish",
    "Crawdaunt",
    "Baltoy",
    "Claydol",
    "Lileep",
    "Cradily",
    "Anorith",
    "Armaldo",
    "Feebas",
    "Milotic",
    "Castform",
    "Kecleon",
    "Shuppet",
    "Banette",
    "Duskull",
    "Dusclops",
    "Tropius",
    "Chimecho",
    "Absol",
    "Wynaut",
    "Snorunt",
    "Glalie",
    "Spheal",
    "Sealeo",
    "Walrein",
    "Clamperl",
    "Huntail",
    "Gorebyss",
    "Relicanth",
    "Luvdisc",
    "Bagon",
    "Shelgon",
    "Salamence",
    "Beldum",
    "Metang",
    "Metagross",
    "Regirock",
    "Regice",
    "Registeel",
    "Latias",
    "Latios",
    "Kyogre",
    "Groudon",
    "Rayquaza",
    "Jirachi",
    "Deoxys",
    "Turtwig",
    "Grotle",
    "Torterra",
    "Chimchar",
    "Monferno",
    "Infernape",
    "Piplup",
    "Prinplup",
    "Empoleon",
    "Starly",
    "Staravia",
    "Staraptor",
    "Bidoof",
    "Bibarel",
    "Kricketot",
    "Kricketune",
    "Shinx",
    "Luxio",
    "Luxray",
    "Budew",
    "Roserade",
    "Cranidos",
    "Rampardos",
    "Shieldon",
    "Bastiodon",
    "Burmy",
    "Wormadam",
    "Mothim",
    "Combee",
    "Vespiquen",
    "Pachirisu",
    "Buizel",
    "Floatzel",
    "Cherubi",
    "Cherrim",
    "Shellos",
    "Gastrodon",
    "Ambipom",
    "Drifloon",
    "Drifblim",
    "Buneary",
    "Lopunny",
    "Mismagius",
    "Honchkrow",
    "Glameow",
    "Purugly",
    "Chingling",
    "Stunky",
    "Skuntank",
    "Bronzor",
    "Bronzong",
    "Bonsly",
    "Mime Jr.",
    "Happiny",
    "Chatot",
    "Spiritomb",
    "Gible",
    "Gabite",
    "Garchomp",
    "Munchlax",
    "Riolu",
    "Lucario",
    "Hippopotas",
    "Hippowdon",
    "Skorupi",
    "Drapion",
    "Croagunk",
    "Toxicroak",
    "Carnivine",
    "Finneon",
    "Lumineon",
    "Mantyke",
    "Snover",
    "Abomasnow",
    "Weavile",
    "Magnezone",
    "Lickilicky",
    "Rhyperior",
    "Tangrowth",
    "Electivire",
    "Magmortar",
    "Togekiss",
    "Yanmega",
    "Leafeon",
    "Glaceon",
    "Gliscor",
    "Mamoswine",
    "Porygon-Z",
    "Gallade",
    "Probopass",
    "Dusknoir",
    "Froslass",
    "Rotom",
    "Uxie",
    "Mesprit",
    "Azelf",
    "Dialga",
    "Palkia",
    "Heatran",
    "Regigigas",
    "Giratina",
    "Cresselia",
    "Phione",
    "Manaphy",
    "Darkrai",
    "Shaymin",
    "Arceus",
    "Victini",
    "Snivy",
    "Servine",
    "Serperior",
    "Tepig",
    "Pignite",
    "Emboar",
    "Oshawott",
    "Dewott",
    "Samurott",
    "Patrat",
    "Watchog",
    "Lillipup",
    "Herdier",
    "Stoutland",
    "Purrloin",
    "Liepard",
    "Pansage",
    "Simisage",
    "Pansear",
    "Simisear",
    "Panpour",
    "Simipour",
    "Munna",
    "Musharna",
    "Pidove",
    "Tranquill",
    "Unfezant",
    "Blitzle",
    "Zebstrika",
    "Roggenrola",
    "Boldore",
    "Gigalith",
    "Woobat",
    "Swoobat",
    "Drilbur",
    "Excadrill",
    "Audino",
    "Timburr",
    "Gurdurr",
    "Conkeldurr",
    "Tympole",
    "Palpitoad",
    "Seismitoad",
    "Throh",
    "Sawk",
    "Sewaddle",
    "Swadloon",
    "Leavanny",
    "Venipede",
    "Whirlipede",
    "Scolipede",
    "Cottonee",
    "Whimsicott",
    "Petilil",
    "Lilligant",
    "Basculin",
    "Sandile",
    "Krokorok",
    "Krookodile",
    "Darumaka",
    "Darmanitan",
    "Maractus",
    "Dwebble",
    "Crustle",
    "Scraggy",
    "Scrafty",
    "Sigilyph",
    "Yamask",
    "Cofagrigus",
    "Tirtouga",
    "Carracosta",
    "Archen",
    "Archeops",
    "Trubbish",
    "Garbodor",
    "Zorua",
    "Zoroark",
    "Minccino",
    "Cinccino",
    "Gothita",
    "Gothorita",
    "Gothitelle",
    "Solosis",
    "Duosion",
    "Reuniclus",
    "Ducklett",
    "Swanna",
    "Vanillite",
    "Vanillish",
    "Vanilluxe",
    "Deerling",
    "Sawsbuck",
    "Emolga",
    "Karrablast",
    "Escavalier",
    "Foongus",
    "Amoonguss",
    "Frillish",
    "Jellicent",
    "Alomomola",
    "Joltik",
    "Galvantula",
    "Ferroseed",
    "Ferrothorn",
    "Klink",
    "Klang",
    "Klinklang",
    "Tynamo",
    "Eelektrik",
    "Eelektross",
    "Elgyem",
    "Beheeyem",
    "Litwick",
    "Lampent",
    "Chandelure",
    "Axew",
    "Fraxure",
    "Haxorus",
    "Cubchoo",
    "Beartic",
    "Cryogonal",
    "Shelmet",
    "Accelgor",
    "Stunfisk",
    "Mienfoo",
    "Mienshao",
    "Druddigon",
    "Golett",
    "Golurk",
    "Pawniard",
    "Bisharp",
    "Bouffalant",
    "Rufflet",
    "Braviary",
    "Vullaby",
    "Mandibuzz",
    "Heatmor",
    "Durant",
    "Deino",
    "Zweilous",
    "Hydreigon",
    "Larvesta",
    "Volcarona",
    "Cobalion",
    "Terrakion",
    "Virizion",
    "Tornadus",
    "Thundurus",
    "Reshiram",
    "Zekrom",
    "Landorus",
    "Kyurem",
    "Keldeo",
    "Meloetta",
    "Genesect",
    "Chespin",
    "Quilladin",
    "Chesnaught",
    "Fennekin",
    "Braixen",
    "Delphox",
    "Froakie",
    "Frogadier",
    "Greninja",
    "Bunnelby",
    "Diggersby",
    "Fletchling",
    "Fletchinder",
    "Talonflame",
    "Scatterbug",
    "Spewpa",
    "Vivillon",
    "Litleo",
    "Pyroar",
    "Flabébé",
    "Floette",
    "Florges",
    "Skiddo",
    "Gogoat",
    "Pancham",
    "Pangoro",
    "Furfrou",
    "Espurr",
    "Meowstic",
    "Honedge",
    "Doublade",
    "Aegislash",
    "Spritzee",
    "Aromatisse",
    "Swirlix",
    "Slurpuff",
    "Inkay",
    "Malamar",
    "Binacle",
    "Barbaracle",
    "Skrelp",
    "Dragalge",
    "Clauncher",
    "Clawitzer",
    "Helioptile",
    "Heliolisk",
    "Tyrunt",
    "Tyrantrum",
    "Amaura",
    "Aurorus",
    "Sylveon",
    "Hawlucha",
    "Dedenne",
    "Carbink",
    "Goomy",
    "Sliggoo",
    "Goodra",
    "Klefki",
    "Phantump",
    "Trevenant",
    "Pumpkaboo",
    "Gourgeist",
    "Bergmite",
    "Avalugg",
    "Noibat",
    "Noivern",
    "Xerneas",
    "Yveltal",
    "Zygarde",
    "Diancie",
    "Hoopa",
    "Volcanion",
    "Rowlet",
    "Dartrix",
    "Decidueye",
    "Litten",
    "Torracat",
    "Incineroar",
    "Popplio",
    "Brionne",
    "Primarina",
    "Pikipek",
    "Trumbeak",
    "Toucannon",
    "Yungoos",
    "Gumshoos",
    "Grubbin",
    "Charjabug",
    "Vikavolt",
    "Crabrawler",
    "Crabominable",
    "Oricorio",
    "Cutiefly",
    "Ribombee",
    "Rockruff",
    "Lycanroc",
    "Wishiwashi",
    "Mareanie",
    "Toxapex",
    "Mudbray",
    "Mudsdale",
    "Dewpider",
    "Araquanid",
    "Fomantis",
    "Lurantis",
    "Morelull",
    "Shiinotic",
    "Salandit",
    "Salazzle",
    "Stufful",
    "Bewear",
    "Bounsweet",
    "Steenee",
    "Tsareena",
    "Comfey",
    "Oranguru",
    "Passimian",
    "Wimpod",
    "Golisopod",
    "Sandygast",
    "Palossand",
    "Pyukumuku",
    "Type: Null",
    "Silvally",
    "Minior",
    "Komala",
    "Turtonator",
    "Togedemaru",
    "Mimikyu",
    "Bruxish",
    "Drampa",
    "Dhelmise",
    "Jangmo-o",
    "Hakamo-o",
    "Kommo-o",
    "Tapu Koko",
    "Tapu Lele",
    "Tapu Bulu",
    "Tapu Fini",
    "Cosmog",
    "Cosmoem",
    "Solgaleo",
    "Lunala",
    "Nihilego",
    "Buzzwole",
    "Pheromosa",
    "Xurkitree",
    "Celesteela",
    "Kartana",
    "Guzzlord",
    "Necrozma",
    "Magearna",
    "Marshadow",
    "Poipole",
    "Naganadel",
    "Stakataka",
    "Blacephalon",
    "Zeraora",
    "Meltan",
    "Melmetal",
    "Grookey",
    "Thwackey",
    "Rillaboom",
    "Scorbunny",
    "Raboot",
    "Cinderace",
    "Sobble",
    "Drizzile",
    "Inteleon",
    "Skwovet",
    "Greedent",
    "Rookidee",
    "Corvisquire",
    "Corviknight",
    "Blipbug",
    "Dottler",
    "Orbeetle",
    "Nickit",
    "Thievul",
    "Gossifleur",
    "Eldegoss",
    "Wooloo",
    "Dubwool",
    "Chewtle",
    "Drednaw",
    "Yamper",
    "Boltund",
    "Rolycoly",
    "Carkol",
    "Coalossal",
    "Applin",
    "Flapple",
    "Appletun",
    "Silicobra",
    "Sandaconda",
    "Cramorant",
    "Arrokuda",
    "Barraskewda",
    "Toxel",
    "Toxtricity",
    "Sizzlipede",
    "Centiskorch",
    "Clobbopus",
    "Grapploct",
    "Sinistea",
    "Polteageist",
    "Hatenna",
    "Hattrem",
    "Hatterene",
    "Impidimp",
    "Morgrem",
    "Grimmsnarl",
    "Obstagoon",
    "Perrserker",
    "Cursola",
    "Sirfetch'd",
    "Mr. Rime",
    "Runerigus",
    "Milcery",
    "Alcremie",
    "Falinks",
    "Pincurchin",
    "Snom",
    "Frosmoth",
    "Stonjourner",
    "Eiscue",
    "Indeedee",
    "Morpeko",
    "Cufant",
    "Copperajah",
    "Dracozolt",
    "Arctozolt",
    "Dracovish",
    "Arctovish",
    "Duraludon",
    "Dreepy",
    "Drakloak",
    "Dragapult",
    "Zacian",
    "Zamazenta",
    "Eternatus",
    "Kubfu",
    "Urshifu",
    "Zarude",
    "Regieleki",
    "Regidrago",
    "Glastrier",
    "Spectrier",
    "Calyrex",
    "Wyrdeer",
    "Kleavor",
    "Ursaluna",
    "Basculegion",
    "Sneasler",
    "Overqwil",
    "Enamorus",
    "Sprigatito",
    "Floragato",
    "Meowscarada",
    "Fuecoco",
    "Crocalor",
    "Skeledirge",
    "Quaxly",
    "Quaxwell",
    "Quaquaval",
    "Lechonk",
    "Oinkologne",
    "Tarountula",
    "Spidops",
    "Nymble",
    "Lokix",
    "Pawmi",
    "Pawmo",
    "Pawmot",
    "Tandemaus",
    "Maushold",
    "Fidough",
    "Dachsbun",
    "Smoliv",
    "Dolliv",
    "Arboliva",
    "Squawkabilly",
    "Nacli",
    "Naclstack",
    "Garganacl",
    "Charcadet",
    "Armarouge",
    "Ceruledge",
    "Tadbulb",
    "Bellibolt",
    "Wattrel",
    "Kilowattrel",
    "Maschiff",
    "Mabosstiff",
    "Shroodle",
    "Grafaiai",
    "Bramblin",
    "Brambleghast",
    "Toedscool",
    "Toedscruel",
    "Klawf",
    "Capsakid",
    "Scovillain",
    "Rellor",
    "Rabsca",
    "Flittle",
    "Espathra",
    "Tinkatink",
    "Tinkatuff",
    "Tinkaton",
    "Wiglett",
    "Wugtrio",
    "Bombirdier",
    "Finizen",
    "Palafin",
    "Varoom",
    "Revavroom",
    "Cyclizar",
    "Orthworm",
    "Glimmet",
    "Glimmora",
    "Greavard",
    "Houndstone",
    "Flamigo",
    "Cetoddle",
    "Cetitan",
    "Veluza",
    "Dondozo",
    "Tatsugiri",
    "Annihilape",
    "Clodsire",
    "Farigiraf",
    "Dudunsparce",
    "Kingambit",
    "Great Tusk",
    "Scream Tail",
    "Brute Bonnet",
    "Flutter Mane",
    "Slither Wing",
    "Sandy Shocks",
    "Iron Treads",
    "Iron Bundle",
    "Iron Hands",
    "Iron Jugulis",
    "Iron Moth",
    "Iron Thorns",
    "Frigibax",
    "Arctibax",
    "Baxcalibur",
    "Gimmighoul",
    "Gholdengo",
    "Wo-Chien",
    "Chien-Pao",
    "Ting-Lu",
    "Chi-Yu",
    "Roaring Moon",
    "Iron Valiant",
    "Koraidon",
    "Miraidon",
    "Walking Wake",
    "Iron Leaves"
  ]